// This file is automatically generated. Do not edit it directly.
// Safe supabase client — falls back to a minimal mock when env is not configured
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function makeMock() {
  const noopSub = { unsubscribe: () => {} };
  return {
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: noopSub } }),
      getSession: async () => ({ data: { session: null } }),
      signUp: async (_: any) => ({ data: { user: null }, error: null }),
      signInWithPassword: async (_: any) => ({ data: null, error: null }),
      signOut: async () => ({ error: null }),
    },
    from: (_: string) => ({
      select: async () => ({ data: null, error: null }),
      insert: async () => ({ data: null, error: null }),
      update: async () => ({ data: null, error: null }),
      delete: async () => ({ data: null, error: null }),
      maybeSingle: async () => ({ data: null, error: null }),
      eq: function () { return this; },
    }),
    // minimal RPC/postgrest placeholders
    rpc: async () => ({ data: null, error: null }),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

export const supabase = (SUPABASE_URL && SUPABASE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : makeMock();

